### ISSUE TITLE
Adding output formatting options

### ISSUE THREAD

**Issue by jonabend-uptake** [LukeSavefrogs/column_ansi#1]
I found you script and it solved a problem that I have had for a while with colored output and limits with `column`.

The performance you achieve using perl is amazing.

I have added some additional functionality to make "fancy ASCII" tables and would like to give the updates back to you for consideration/inclusion, but was not able to submit it as a branch on your repo.

So here it is attached as a txt file.

Thank you for sharing your code!

```
	-p INTERGER, --padding INTERGER
		Specify the number of spaces to pad fields(default is zero spaces).

	-h,  --header
		First line of file will be a header with a row separator added after the first row outputted.

	-b,  --border
		Add borders around outside of output table. (Uses OUTPUT SEPARATOR)

	-f,  --fancy
		Add borders, output_separator = "|", and padding=1

```

[column_ansi.sh.txt](https://github.com/LukeSavefrogs/column_ansi/files/8846911/column_ansi.sh.txt)

(I did also change the default separator to "comma")

**Comment by LukeSavefrogs** [comment]
Hi @jonabend-uptake!
Thank you for your kind comments 😊

I'm happy you found it **useful** and even more happy you're sharing new ideas!

To be honest, i initially thought of `column_ansi` as a direct replacement for `column`, so that anyone could go and literally make an alias and it would work....
But it would make more sense to do as you suggested and add useful features, since i found myself having the same problem too some time ago.

### 👀 Proposal 👀 
I'll definetly look into your code and try to break down what's going on...
It would really be a **great help** if you could:
- **Comment** the code you made (maybe prefixing it like `# [jonabend-uptake] Your comment here`, so I know that it's yours)
- Elaborate a bit more on **what the `--fancy` option does** (is it just equivalent to the more verbose `--border --output-separator "|" --padding 1`?)

If you could do that it would be easier for me to merge the two codes 😄 

I'll try to merge them anyway, so don't feel forced (it will take me time tho). Thanks again for your interest and help 😄 

### 🐛 Bug 🐛
I noticed one thing right away: the `-h` parameter for `--header` overrides the `-h` used for `--help`, so we should change that.

![image](https://user-images.githubusercontent.com/33452387/172496119-d5c5302a-ab23-4eb4-9132-fee3a7041f7d.png)

**Comment by LukeSavefrogs** [comment]
Sorry to answer after so much time, but a lot of things happened... 

The initial project goal was to create a version of `column` working with ANSI escape codes (the one on our servers did not interpret them correctly, maybe because of an outdated version...) with support for a specific subset of `column` original parameters.

Adding custom parameters (not present in the original) therefore is not planned as of now, and while I personally think these could be interesting additions, I don't think it falls into the boundaries of the project nor the gains are worth the time spent.

Feel free to fork the project and proceed on your own 😄

Thank you for taking the time to submit the first issue of this project 🎉
Have a good day! 👋🏻
